version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    volumes:
      #diretório dos dados
      #- repositório_local:repositório_do_container
      - dados:/var/lib/postgresql/data
      #diretório dos scripts
      - ./scripts:/scripts
      #Para executar scripts na inicialização do container, usa-se o /docker-entrypoint-initdb.d conforme documentação constante em https://hub.docker.com/_/postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    # As dependencias do serviço serão inicializadas juntamente ao serviço atual
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      #aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=nome_a_sobrescrever
      - DB_USER=postgres
      - DB_HOST=db
      - REDIS_HOST=queue
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
    environment:
      - REDIS_HOST=queue
